# export QT_AUTO_SCREEN_SCALE_FACTOR=0
# export QT_SCALE_FACTOR=1
# export QT_SCREEN_SCALE_FACTORS="1;1;1"
# export GDK_SCALE=1
# export GDK_DPI_SCALE=1
export EDITOR="vim"
# export READER="zathura"
export VISUAL="vim"
export TERMINAL="yakuake"
export BROWSER="firefox"
export VIDEO="mpv"
# export IMAGE="sxiv"
export COLORTERM="truecolor"
export OPENER="xdg-open"
export PAGER="less"
# export WM="bspwm"
